# Generated by Django 3.1.1 on 2020-09-09 09:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usernew',
            fields=[
                ('key_img', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='girish', max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='image_profile/')),
            ],
        ),
    ]
