# Generated by Django 3.1.1 on 2020-09-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200909_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernew',
            name='image',
            field=models.ImageField(default='image_profile/my_pic.jpg', null=True, upload_to='image_profile/'),
        ),
    ]
