# Generated by Django 3.1.1 on 2020-09-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usernew',
        ),
    ]
