# Generated by Django 3.1.1 on 2020-09-13 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_profile_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encrypt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_kek', models.CharField(default=b';.5?\x89\xe3Y|', max_length=1000)),
                ('iv_kek', models.CharField(default=b'y\n\xd5\x92\x89\x98\x1c\xed\x8e\xf9h&\x022\xe6R', max_length=1000)),
                ('iv_dek', models.CharField(default=b'\x02\xc2z\x0bL}\x16\x11\x01n\xc9b\xcc<b\xbd', max_length=1000)),
                ('encrypted_dek', models.CharField(default=None, max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
