# Generated by Django 3.1.1 on 2020-09-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_encrypt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='encrypted_dek',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.CharField(default=b'N\xd9I\xec\xd0\xe2<\xe0\x06IqQ\xca\xa0L\x9d', max_length=1000),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.CharField(default=b',E\xd7\xa8\xe2\xfe\xa6\xa7#SU\xb1\xa5k&&', max_length=1000),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.CharField(default=b'\xc0\xe9)\x82:\xffo\x15', max_length=1000),
        ),
    ]
