# Generated by Django 3.1.1 on 2020-09-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200913_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='encrypted_dek',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.CharField(default=b'\x8f\xd8+?\x88?E\xe9\x1e\x1aPY\xa0\xc0G-', max_length=1000),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.CharField(default=b'H\\f\x90@\x92!\xc6\xa6\x1c\x9c\xaa\x8d\xdc{$', max_length=1000),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.CharField(default=b'F\xf8j\xef\x9cS\x9b@', max_length=1000),
        ),
    ]
