# Generated by Django 3.1.1 on 2020-09-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200913_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='encrypted_dek',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.CharField(default=b'\xad\x87\xed\xac\xc7\xff\xae\xc6$\xa6\xa4\x90h\x10\xe8T', max_length=1000),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.CharField(default=b'Y\xfc\x84\xcc!\xb7\xbf?\xeb\xd5\x93\x90\xf9\xe4]\xd7', max_length=1000),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.CharField(default=b'\xac)Q\x89\xe13\x11\x0b', max_length=1000),
        ),
    ]
