# Generated by Django 3.1.1 on 2020-09-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200913_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.CharField(default=b'\x9a\xb0:\xab\xab\xefN\xf9\xe9\xd6\x03\xa3\x17\xc3\xb3;', max_length=1000),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.CharField(default=b'\xfeT\x8a\xfb\xa3c0\xd0#\x83\x8dW\x847\x8b,', max_length=1000),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.CharField(default=b'\x89\x1d?\x17\\\xc3\xe5\xef', max_length=1000),
        ),
    ]
