# Generated by Django 3.1.1 on 2020-09-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200913_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.CharField(default=b'\xc4a\x7f{\xd5e\xeb\x16E%\x18t$ \n\x9a', max_length=1000),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.CharField(default=b'\xe8\x90\x03L\x8f68\xf4@\xf4\x8dCA0\x93\x80', max_length=1000),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.CharField(default=b'9#\x89,\\\xfa\xce\x04', max_length=1000),
        ),
    ]
