# Generated by Django 3.1.1 on 2020-09-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200913_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.CharField(default=b's\xd0V?\xff\x95\x1es\xd5\xe2\x81\\Z\x7f\xaa\xa1', max_length=1000),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.CharField(default=b'\x84\\\x86\xbbU\xa9\xf1\x1f\xe7\xfb\\>\xcc\x0ea\xd9', max_length=1000),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.CharField(default=b'\xe8\xf6J\x1enT\xec\xce', max_length=1000),
        ),
    ]
