# Generated by Django 3.1.1 on 2020-09-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200913_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b'5\xd2?\x1d\x08\xab2\xe3q\x10c\x89\x8e?\xd0Y'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'\x85\xa4\xbd\x98\xb46\xd3\xc6L\x99\xa3\x0c\\\x8c\x8f3'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'CpD\xcbH\x19\x7f\xf4'),
        ),
    ]
