# Generated by Django 3.1.1 on 2020-09-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200913_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='encrypted_dek',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b"PTM'\xa2\xcb\x8cI\xd2\xf1%L\xe3\xbf\xa6\xde"),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'eu\xab\xa9\xa5\xc1\xfbpa\xa6\xaf,\xb6}\xe9\xb7'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'\x1d\xce\xe1\xbc\x1e\x19\xa6j'),
        ),
    ]
