# Generated by Django 3.1.1 on 2020-09-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200913_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b'\xc2-"]\xef\x03\x8fmF\x1e\xbc\xf4\xca\x95wu'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'r\xa4c\xbb\x80\x18\x03\r\x1f\xbe\x9f\xf9\xd9\x8a\xeap'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'\x12\xe1\x8c\xbb\x05E\x98\x03'),
        ),
    ]
