# Generated by Django 3.1.1 on 2020-09-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200914_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b'\x8dT\xacoU\xa1\x03\x9c\xb3\xce\xa14fS\xca\xf7'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'\x94:\xbe\xa7\x9c\xe0\xe1\xc7\x14\xca\x0c\x951\xef\xc4\xbb'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'e\xcd/1\x19\xf5 \xc2'),
        ),
    ]
