# Generated by Django 3.1.1 on 2020-09-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200914_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b'6O\x98\xf4\xc3\x88"&)\xceK\xacGNOp'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'\x9e\xbf\x9e\x1fPS\x94V\x06$\xc1n\xb9\xed\xbb\x89'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'(\xa0\xb3\xcb\xda\x13#\xe5'),
        ),
    ]
