# Generated by Django 3.1.1 on 2020-09-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200914_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b'tr\xca\x00\x86\x16)\x9f\x9b7UI]\x82\x9b\x01'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'\x899P20\\\xf6G\xb7Y_\x9e\\\r\xae\xdb'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'N\x07\xc3\xf4\xc0\xe0b\x1f'),
        ),
    ]
