# Generated by Django 3.1.1 on 2020-09-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200914_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b'\x83]\xfdl\xee\xd6\x15\x8e\x0f;\xb7\xe8(\x9d^7'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b"\xe6z\x98\xc4\x96\xe8j'\x08.+\xa7\x04\x05\xaf\x06"),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'\xf4\xa0L\x92\x0b<\x00\x16'),
        ),
    ]
