# Generated by Django 3.1.1 on 2020-09-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200914_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b'\xf9uq\x80\x08\xfd\xc1\xbd\xb9\x8f&\xb87q\xf3\xbc'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'\x93\xec\x11\xfcu!\x8d\xfb\x0e\xe1\n\xad\x82Z;\xb6'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'/\x9d\xd5r\xcc\x9fd,'),
        ),
    ]
