# Generated by Django 3.1.1 on 2020-09-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200914_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b'\xc3q\xd5\xbf\xef\xe3v\x9cc\x0f\x07\xfb\xec\xb5\xb7\xee'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'-\x14A\xbb\xcc\xc1\x05jKP\xa9\xe0\xf5\xd1\xe4\xbf'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'\xba\x8dvg\x1a\xc0O\xe9'),
        ),
    ]
