# Generated by Django 3.1.1 on 2020-09-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200914_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b';\xca\xfd\xf4\xe1\xd0\xae\x1b\x04\xf4\xcc\xfe\xeb\xbdG\x9b'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'#Q\xacW\x85\xf8\xd2\xf5\xb0\x8a\x96(Yk$\x9d'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'\x80\x90e\\dj\xe2z'),
        ),
    ]
