# Generated by Django 3.1.1 on 2020-09-14 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0025_auto_20200914_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b'\xb6\xfc\x9e\x9aC\x11\xf9\x98\xe0\xc8\x90\xa9\x94\xc7\x16\xee'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'\xb3Z\x84\x11\xf3\xa6L\xb07\xf8O/\xff\x8f\xf7\xf0'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'r}p"\x1c\x9b\xb5\x01'),
        ),
        migrations.CreateModel(
            name='ChatEncrypt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_kek', models.BinaryField(default=b'\x00\xc8\x00G\x021f\xb6')),
                ('iv_kek', models.BinaryField(default=b'\x89\xa3\xa4\xed\xe2?7\xc90\xc2$\x96!x%e')),
                ('encrypted_private', models.BinaryField(blank=True, null=True)),
                ('public', models.BinaryField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
