# Generated by Django 3.1.1 on 2020-09-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200914_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatencrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'\x107\x12\x83\x0b\xc3n\x98\xf6yiBq\xb5\xea\xa3'),
        ),
        migrations.AlterField(
            model_name='chatencrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'W)\x9d~\xc5\x05Yv'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b'\xc7b\xcb~R*\xe5\x19\x17\xf7\x82\x91\x12\xcc1\xff'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'\xfeS\xee0\xc9\x0e\x86\x85\xc5F\xbd)<\xff@\xf7'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'\n\x1d0sF\xcc^T'),
        ),
    ]
