# Generated by Django 3.1.1 on 2020-09-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20200914_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatencrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'\x84\xc2K\x17\x84\x98\x82f\xb2\x96Th\xfc?\xd3\x14'),
        ),
        migrations.AlterField(
            model_name='chatencrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'9\xec\x8c>\x93I)\x8b'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b'\xb2J\xf1X\xcc\xf0p\xba@\xf3\xe7c\x83\xeb\xe2='),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'\xa4z\x8b\xf3\x8fu9\xac\xd2Y\xa9^\xa6\xf0\xc7\x97'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'%\xa7\xa5(\xaa\x14\x15j'),
        ),
    ]
