# Generated by Django 3.1.1 on 2020-09-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20200914_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatencrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'@\xe0\xbb\xf0\xbe\xd2\xf4\xe8Ws>\x0bx\xa9\x9c\x96'),
        ),
        migrations.AlterField(
            model_name='chatencrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'j]gO\x9cV\x7f\xc3'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b'\xa0\xfa`\xea\x96\x93\x9eJ\x02\x8f\xdf\xc4)\x13}\x9e'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'\x99\xeeR\x82X}\x90\xde`2z\xd7A\xa1\x18\x94'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'\x84;\xdd\xd5\xc6j\xdf\x10'),
        ),
    ]
