# Generated by Django 3.1.1 on 2020-09-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20200914_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatencrypt',
            name='public',
        ),
        migrations.AddField(
            model_name='chatencrypt',
            name='public_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatencrypt',
            name='public_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatencrypt',
            name='iv_kek',
            field=models.BinaryField(default=b"/HP\xc4h\xeb\xaa>\xe7\xea'\xebB\x8cP\t"),
        ),
        migrations.AlterField(
            model_name='chatencrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'\x8c\xaa\xb9\x94p\xaahe'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b'\x0eD\xd5\xe9)=\x0c\xa5\xc5_Q\r\xabp=\xdd'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'C\xc4\xbb\xf5\xd8\x84EB\tr\r\xdfL\x82\x04!'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b's\x8f%\x8c\xb4\xe3\xa7\xc9'),
        ),
    ]
