# Generated by Django 3.1.1 on 2020-09-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20200914_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatencrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'\xe4\xca7\x8b\x8dK \xb0\xf7\xff\xb9Ujt\x83,'),
        ),
        migrations.AlterField(
            model_name='chatencrypt',
            name='public_x',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatencrypt',
            name='public_y',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatencrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'\xb8\x04&G\xca\xb3\xc3B'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b'\xde\x89\x14_s\xc1Ce\xc6)u\x9e6\xd0\x86\xae'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'\xda\x06\t\xbd\xd7\xe9\xcc\xc6\xb0(\x06\x17\x8e\xfa\n\x8e'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'\x98t\xf7q\x8c\x91\xcd\xea'),
        ),
    ]
