# Generated by Django 3.1.1 on 2020-09-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20200914_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatencrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'\xca\x1bc\x988\xce\xea\xd6\xc0\x88\xa9\x93\xc7?\xb2q'),
        ),
        migrations.AlterField(
            model_name='chatencrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'4\xa8\x07.U\xf3\xd4\xe8'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b'\xbf\xcb\x9e2\xa1\xda\x9f9\x11\\G^^\xc7.e'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'eB\xbf+\xdd\xcb\x19\x8djY4% \xba;x'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'\xea\xd2tQ\xb6\x1a\xcc\x9c'),
        ),
    ]
