# Generated by Django 3.1.1 on 2020-09-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20200915_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatencrypt',
            name='iv_kek',
            field=models.BinaryField(default=b'@\xc7\xb5 \xfe\xea\xdd\x80\xff\xb4\xc2\x96\xd6\x9d\x17\x02'),
        ),
        migrations.AlterField(
            model_name='chatencrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'\x02\x98n\xb8\x85\x9a\x87\xd5'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_dek',
            field=models.BinaryField(default=b'e\x1a\xba}\x1b\xefLlQ\xd2\x12Q\x96\xb9(\x84'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='iv_kek',
            field=models.BinaryField(default=b's5\x81P\xa12\x0c\x9er\xe3\x18\xcad)\xd9\xc1'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='salt_kek',
            field=models.BinaryField(default=b'yHX\xa9\x0f\x15\tM'),
        ),
    ]
