# Generated by Django 3.1.1 on 2020-09-14 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0002_auto_20200914_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatp2p',
            name='last_msg_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
