# Generated by Django 3.1.1 on 2020-09-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_auto_20200914_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatp2p',
            name='username1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatp2p',
            name='username2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
