# Generated by Django 3.1.1 on 2020-09-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_chatp2p_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='message',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
