# Generated by Django 3.1.1 on 2020-09-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_auto_20200914_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='message2',
        ),
    ]
