# Generated by Django 3.1.1 on 2020-09-15 04:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_auto_20200915_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='id',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='chatp2p',
            name='last_msg_1',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatp2p',
            name='last_msg_2',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatp2p',
            name='iv',
            field=models.BinaryField(default=b'0:\x9b\x03\xf5;\xbf+\xec\xac\xacy\xce\x9b\xdc\xfd'),
        ),
        migrations.AlterField(
            model_name='chatp2p',
            name='last_msg',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
